<?xml version="1.0" encoding="utf-8"?><Database Name="QLBanHang" Class="LINQ_QLBHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=149.28.151.40;Initial Catalog=QLBanHang;User ID=sa" SettingsObjectName="BLL_LINQ.Properties.Settings" SettingsPropertyName="QLBanHangConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MACTHOADON" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MATHUCPHAM" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="THUCPHAM_CHITIETHOADON" Member="THUCPHAM" ThisKey="MATHUCPHAM" OtherKey="MATHUCPHAM" Type="THUCPHAM" IsForeignKey="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THUCPHAM" Member="THUCPHAMs">
    <Type Name="THUCPHAM">
      <Column Name="MATHUCPHAM" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTHUCPHAM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SIZE" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="THUCPHAM_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MATHUCPHAM" OtherKey="MATHUCPHAM" Type="CHITIETHOADON" />
    </Type>
  </Table>
  <Table Name="dbo.DM_MANHINH" Member="DM_MANHINHs">
    <Type Name="DM_MANHINH">
      <Column Name="MAMANHINH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DANHSACHMANHINH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.GIAOHANG" Member="GIAOHANGs">
    <Type Name="GIAOHANG">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="HOADON_GIAOHANG" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="NHANVIEN_GIAOHANG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HINHTHUCTHANHTOAN" Member="HINHTHUCTHANHTOANs">
    <Type Name="HINHTHUCTHANHTOAN">
      <Column Name="MAHINHTHUC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENHINHTHUC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HINHTHUCTHANHTOAN_HOADON" Member="HOADONs" ThisKey="MAHINHTHUC" OtherKey="MAHINHTHUC" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MAHINHTHUC" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MAKHUYENMAI" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DIACHIGIAO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KHOANGCACH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PHIKC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TINHTRANGTHANHTOAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADON" />
      <Association Name="HOADON_GIAOHANG" Member="GIAOHANGs" ThisKey="MAHD" OtherKey="MAHD" Type="GIAOHANG" />
      <Association Name="HINHTHUCTHANHTOAN_HOADON" Member="HINHTHUCTHANHTOAN" ThisKey="MAHINHTHUC" OtherKey="MAHINHTHUC" Type="HINHTHUCTHANHTOAN" IsForeignKey="true" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="KHUYENMAI_HOADON" Member="KHUYENMAI" ThisKey="MAKHUYENMAI" OtherKey="MAKHUYENMAI" Type="KHUYENMAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TAIKHOAN_KH" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKHUYENMAI" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PHANTRAMKM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="KHUYENMAI_HOADON" Member="HOADONs" ThisKey="MAKHUYENMAI" OtherKey="MAKHUYENMAI" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IMAGE" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="NHANVIEN_GIAOHANG" Member="GIAOHANGs" ThisKey="MANV" OtherKey="MANV" Type="GIAOHANG" />
      <Association Name="NHANVIEN_QL_NGUOIDUNG" Member="QL_NGUOIDUNGs" ThisKey="MANV" OtherKey="MANV" Type="QL_NGUOIDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG" Member="QL_NGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
      <Association Name="NHANVIEN_QL_NGUOIDUNG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs">
    <Type Name="QL_NGUOIDUNGNHOMNGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNG" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNGs">
    <Type Name="QL_NHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PHANQUYEN" Member="QL_PHANQUYENs">
    <Type Name="QL_PHANQUYEN">
      <Column Name="MANHOM" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMANHINH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="DM_MANHINH" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="DM_MANHINH" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
</Database>